blueprint:
  name: IKEA Tradfri on/off Button E1743 - Triggered by actions for Z2M 2.0
  description: Blueprint for Ikea Tradfri on/off Button E1743. Based on the work of [Danieldz](https://community.home-assistant.io/u/Danieldz/).
  domain: automation
  input:
    button:
      name: Remote
      description: IKEA Tradfri on/off Button to use.
      selector:
        device:
          filter:
            - integration: mqtt
              manufacturer: IKEA
          multiple: false
    on_short:
      name: Action when On sended
      description: Action to run when On-Button is shortly pressed
      default: []
      selector:
        action: {}
    off_short:
      name: Action when Off sended
      description: Action to run when Off-Button is shortly pressed
      default: []
      selector:
        action: {}
    on_long:
      name: Action when Brightness_move_up sended
      description: Action to run when On-Button is long pressed
      default: []
      selector:
        action: {}
    off_long:
      name: Action when brightness_move_down sended
      description: Action to run when Off-Button is long pressed
      default: []
      selector:
        action: {}
    long_stopped:
      name: Action when brightness_stop sended
      description: Action to run when a long pressed button is lifted
      default: []
      selector:
        action: {}
mode: restart
max_exceeded: silent
trigger:
- domain: mqtt
  device_id: !input button
  type: action
  subtype: "off"
  trigger: device
  id: 'off'
- domain: mqtt
  device_id: !input button
  type: action
  subtype: "on"
  trigger: device
  id: 'on'
- domain: mqtt
  device_id: !input button
  type: action
  subtype: brightness_move_up
  trigger: device
  id: long_I
- domain: mqtt
  device_id: !input button
  type: action
  subtype: brightness_move_down
  trigger: device
  id: long_O
- domain: mqtt
  device_id: !input button
  type: action
  subtype: brightness_stop
  trigger: device
  id: long_lifted
condition: []
action:
- choose:
  - conditions:
    - condition: trigger
      id: 'off'
    sequence: !input off_short
  - conditions:
    - condition: trigger
      id: 'on'
    sequence: !input on_short
  - conditions:
    - condition: trigger
      id: long_I
    sequence: !input on_long
  - conditions:
    - condition: trigger
      id: long_O
    sequence: !input off_long
  - conditions:
    - condition: trigger
      id: long_lifted
    sequence: !input long_stopped
